#----------------------------------------------------------------------
#  pla-util - A power line adapter utility
#  Copyright (C) 2016-2023 John Serock
#
#  This file is part of pla-util.
#
#  pla-util is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  pla-util is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#  SPDX-License-Identifier: GPL-3.0-or-later
#----------------------------------------------------------------------
name = "pla_util"
description = "A power line adapter utility"
version = "2.1.0"
licenses = "GPL-3.0-or-later"
website = "https://github.com/serock/pla-util"

authors = ["John Serock"]
maintainers = ["John Serock <1468970+serock@users.noreply.github.com>"]
maintainers-logins = ["serock"]

executables = ["pla_util"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
"*".ada_version = "ada12"
"*".style_checks = ["-gnaty3aAbBcdefhiIklnoOprsStux"]

development.compile_checks = ["-gnateu", "-gnatf", "-gnatwa", "-gnatVa", "-gnatwd", "-gnatw.d", "-gnatwh", "-gnatw.h", "-gnatw.j", "-gnatw.k", "-gnatwl", "-gnatw.l", "-gnatwo", "-gnatw.o", "-gnatw.q", "-gnatw_r", "-gnatw.s", "-gnatwt", "-gnatw.u", "-gnatw.w"]
development.contracts = ["-gnata"]
development.debug_info = ["-g", "-gnateE"]
development.optimization = []
development.runtime_checks = ["-gnatE", "-gnato", "-fstack-check"]

validation.compile_checks = ["-gnateu", "-gnatf", "-gnatwa", "-gnatVa", "-gnatwd", "-gnatw.d", "-gnatwh", "-gnatw.h", "-gnatw.j", "-gnatw.k", "-gnatwl", "-gnatw.l", "-gnatwo", "-gnatw.o", "-gnatw.q", "-gnatw_r", "-gnatw.s", "-gnatwt", "-gnatw.u", "-gnatw.w"]
validation.contracts = ["-gnata"]
validation.debug_info = ["-g", "-gnateE"]
validation.optimization = []
validation.runtime_checks = ["-gnatE", "-gnato", "-fstack-check"]
