--  Configuration for pla_util generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Pla_Util_Config is
   pragma Pure;

   Crate_Version : constant String := "2.1.1";
   Crate_Name : constant String := "pla_util";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "suse";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Pla_Util_Config;
